name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: |
          cd backend && npm ci
          cd ../frontend && npm ci
      - name: Run backend lint & tests
        run: |
          cd backend && npm run lint && npm test
      - name: Run frontend lint & tests
        run: |
          cd frontend && npm run lint && npm test
